services:
  - type: web
    name: fishstatik-app # Ganti nama ini jika Anda mau
    env: python
    region: singapore # Pilih region terdekat (cth: singapore)
    plan: free # Mulai dengan 'free', upgrade ke 'starter' jika perlu
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: "/" # Gunakan rute index Anda untuk cek kesehatan
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11 # Sesuaikan dengan versi Python Anda jika perlu